name: filterdata
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'
  


dependencies:
  json_annotation: ^4.5.0

  http: ^0.13.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.11
  
